# Generated by Django 4.0.4 on 2022-05-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100, verbose_name='logradouro')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('localidade', models.CharField(max_length=100, verbose_name='localidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('ibge', models.CharField(max_length=7, verbose_name='código do município')),
                ('gia', models.CharField(blank=True, max_length=10, null=True, verbose_name='GIA')),
                ('ddd', models.CharField(max_length=2, verbose_name='DDD')),
                ('siafi', models.CharField(max_length=10, verbose_name='SIAFI')),
            ],
        ),
    ]
